import "./globals.css";

import {
  ClerkProvider
} from '@clerk/nextjs'
import type { Metadata } from "next";
import { Open_Sans } from 'next/font/google'
import { Toaster } from "sonner";

import QueryProvider from "@/components/providers/query-provider";
import { ThemeProvider } from "@/components/providers/theme-provider"
import { SocketProvider } from "@/components/socket-provider";
import { cn } from "@/lib/utils";

const font = Open_Sans({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={cn(`${font.className}`, 'dark:bg-[#313338]')}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <QueryProvider>
              <Toaster />
              <SocketProvider>
                {children}
              </SocketProvider>
            </QueryProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
